import "./globals.css";
import Navbar from "../components/Shared/Navbar";
import Footer from "../components/Shared/Footer";
import Providers from "@/utils/Providers";
import ClientToaster from "@/utils/ClientToaster";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata = {
  title: "Kicks Front End Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#E7E7E3] max-w-330 mx-auto">
        <Providers>
          <ClientToaster />

          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
