import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Shared/Navbar";
import Footer from "./components/Shared/Footer";

export const metadata: Metadata = {
  title: "Kicks Front End Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#E7E7E3]">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
